spring:
  application:
    name: msclients

server:
  port: 0 #port 0 to create ports randomly and that is not busy

eureka:
  client:
    service-url:
      defaultZone: http://${USERNAME}:${PASSWORD}@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} #will generate random instance id

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log